/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner gates;
        try {
            gates = new Scanner(new File("src/main/resources/gates.js"));

        } catch (FileNotFoundException e) {
            System.out.println("We couldn't find that file.");
            return;
        }
    }
}