/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner gates;
        try {
            gates = new Scanner(new File("src/main/resources/gates.js"));

        } catch (FileNotFoundException e) {
            System.out.println("We couldn't find that file.");
            return;
        }

        int counter = 1;
        String errorString = "";

        while(gates.hasNextLine()){

            counter++;
            String temp = gates.nextLine();
            if(!temp.isBlank()) {

                char endChar = temp.charAt(temp.length() -1);
                if (endChar == ';' || endChar == '{' || endChar == '}' || temp.contains("if") || temp.contains("else")) {
                } else {
                    if(errorString.isBlank()){

                        errorString = "Line " + counter + " is missing ;";
                    } else {
                        errorString = errorString + "\nLine " + counter + " is missing ;";
                    }
                }
              }
        }

        System.out.println(errorString);

    }
}